# App Engine definition file for Telpirion.com
# Copyright 2018-12-23 Eric Schmidt
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Python / AppEngine / Jinja
- url: /js
  static_dir: js
- url: /server
  script: main.app
- url: /api
  script: main.app
# Angular app
- url: /(.*\.js)
  static_files: ng/\1
  upload: ng/(.*\.js)
- url: /(.*\.css)
  static_files: ng/\1
  upload: ng/(.*\.css)
- url: /.*
  static_files: ng/index.html
  upload: ng/index.html
- url: (.*)/
  static_files: ng/index.html
  upload: ng
- url: (.*)
  static_files: ng/index.html
  upload: ng


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest