//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shamepilesoftware_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int HitDice { get; set; }
        public int DamageMax { get; set; }
    }
}
